<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__code_edit</name>
   <tag></tag>
   <elementGuidId>9c8c1c04-7d3c-4adb-a271-99ff4541f6d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;code&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @name = 'code']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;code&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bc46349-e2b5-4588-8edc-c2fca286b9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92c0dc5f-b702-46b4-8051-5714a47e2821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled p-inputtext-fluid</value>
      <webElementGuid>ff6b2e22-2f20-4672-b21d-be38e401892e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>6913a093-9485-4e50-9810-7bdad1b4e202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>fluid</value>
      <webElementGuid>2b57813a-24e2-47de-9302-b9626f401c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>inputtext</value>
      <webElementGuid>2d0cf505-d9b4-4adc-99aa-6bf0e47a38f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>7eef35f0-4e04-44d0-b517-f671c1736dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>name2</value>
      <webElementGuid>f7d16aaf-581a-47f9-885c-f03935ece209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined_accordioncontent_general&quot;)/div[@class=&quot;p-accordioncontent-content&quot;]/div[@class=&quot;flex flex-col gap-4 w-full pt-4&quot;]/div[@class=&quot;flex items-start w-full gap-4&quot;]/div[@class=&quot;flex flex-col gap-1 flex-1&quot;]/div[@class=&quot;p-iconfield&quot;]/input[@class=&quot;p-inputtext p-component p-filled p-inputtext-fluid&quot;]</value>
      <webElementGuid>3ac9cb67-2fe1-43ec-8709-f21563646344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='code']</value>
      <webElementGuid>18a39bca-4706-4965-94ec-700295cd02b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='undefined_accordioncontent_general']/div/div/div[2]/div/div/input</value>
      <webElementGuid>db4b950c-9cd6-4437-8a8b-718cc4e685bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>ce81b56a-d8fb-4629-8f3c-02d7b3bfea93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code']</value>
      <webElementGuid>257b54fb-d686-4e10-b17b-6309c20d526f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
