<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_upload</name>
   <tag></tag>
   <elementGuidId>d6b522c2-a8f6-44ff-a5d1-f0205864c6e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;image&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>466be748-73c7-4e65-b8d5-42761fef6497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEdSURBVHgB5ZRBagIxFIb/pKVYaiHLQrFNb+CydOXsuvQGXkGP4c4jeAOPoIKIS2/gEzduhFkIgouJLygqY0YmQzbqv5nwMnxfEvIC3HqeUCAf+leXVaX3pr4676pSWseLYTCBhQOyD4iqAEpcqrEMWRIvwQkOzfCpgWkLiP9rktyCNHyDl2hFo0FZfc55N/UsifSFp+eWNOnyTlp2zOJmev4ZBeAGqL5i24euRftVbhtmX4+9BNdWfpQcxvwhIInS/4kicEfIwvm4KJcgFNwpCAm3kZdG2QwFdwoS4BuB4E6BgFEIBHcKWKERCJ4hyDx/8oXbuBqNuHEUX6/YdqaEoQRiLpB0fOH3EUej/c2Qrw9coSWNf84LuZ7rx84OFR5/6dZBwBUAAAAASUVORK5CYII=</value>
      <webElementGuid>1ec07556-7c8e-46ce-ac81-3a5093c15aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>e371e503-44c6-4b91-9604-5597f9e3a1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-dialog-mask p-overlay-mask p-overlay-mask-enter&quot;]/div[@class=&quot;p-dialog p-component !p-0&quot;]/div[@class=&quot;p-dialog-content&quot;]/div[@class=&quot;p-card p-component mt-1&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-content&quot;]/div[@class=&quot;flex flex-col gap-4 md:w-1/2 mt-4&quot;]/div[@class=&quot;grid grid-cols-12 gap-2&quot;]/div[@class=&quot;col-span-12 md:col-span-9&quot;]/div[@class=&quot;p-iconfield&quot;]/span[@class=&quot;p-inputicon&quot;]/span[@class=&quot;p-image p-component&quot;]/img[1]</value>
      <webElementGuid>a06225a2-6a97-41de-a1c6-fd23320c8e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='image']</value>
      <webElementGuid>5ce03dfb-05c8-4be5-8625-e5bab5c9792b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>bf19af64-df4d-4e6f-861a-c05e68f1031b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEdSURBVHgB5ZRBagIxFIb/pKVYaiHLQrFNb+CydOXsuvQGXkGP4c4jeAOPoIKIS2/gEzduhFkIgouJLygqY0YmQzbqv5nwMnxfEvIC3HqeUCAf+leXVaX3pr4676pSWseLYTCBhQOyD4iqAEpcqrEMWRIvwQkOzfCpgWkLiP9rktyCNHyDl2hFo0FZfc55N/UsifSFp+eWNOnyTlp2zOJmev4ZBeAGqL5i24euRftVbhtmX4+9BNdWfpQcxvwhIInS/4kicEfIwvm4KJcgFNwpCAm3kZdG2QwFdwoS4BuB4E6BgFEIBHcKWKERCJ4hyDx/8oXbuBqNuHEUX6/YdqaEoQRiLpB0fOH3EUej/c2Qrw9coSWNf84LuZ7rx84OFR5/6dZBwBUAAAAASUVORK5CYII=' and @alt = 'image']</value>
      <webElementGuid>dff302bc-fcef-4ba7-af6c-02e687225580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
