<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Notification_popup</name>
   <tag></tag>
   <elementGuidId>9d4b4de9-3368-4bed-88e7-afbe63ff7efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'p-toast-message-content' and (text() = 'NotificationCreate property specification successfully.' or . = 'NotificationCreate property specification successfully.')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'p-toast-message-content') and contains(normalize-space(.), '${text}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-toast-message-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f7f4196-fed0-4f02-9912-745ffb0dbddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-toast-message-content</value>
      <webElementGuid>5f5ea339-5a19-4872-b209-532cb5ec8a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>messagecontent</value>
      <webElementGuid>b032f68a-2143-4019-9cd5-19eefe138a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NotificationCreate property specification successfully.</value>
      <webElementGuid>fdf7c026-e5ad-4a77-a1a1-789991a67557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;p-toast p-component p-toast-top-right&quot;]/div[1]/div[@class=&quot;p-toast-message p-toast-message-success p-toast-message-leave-active p-toast-message-leave-to&quot;]/div[@class=&quot;p-toast-message-content&quot;]</value>
      <webElementGuid>c35ab1d6-eacc-4921-adc0-625889a0bf4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[7]</value>
      <webElementGuid>c2289ef4-6fa8-488d-bb38-bce6c1a82cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[7]</value>
      <webElementGuid>b87cf278-a0ee-443d-95a0-b0c107423dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>be8bc115-d1b4-4085-bd49-b41c8aecff9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NotificationCreate property specification successfully.' or . = 'NotificationCreate property specification successfully.')]</value>
      <webElementGuid>dbdeac3e-9c91-40ff-bf10-52d2b99a287f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
