<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_p-toast-message-content</name>
   <tag></tag>
   <elementGuidId>8ae57724-1667-4f44-950a-ccacf38dc9c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'NotificationUpdate property specification successfully.' or . = 'NotificationUpdate property specification successfully.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79933702-d3f7-4c47-b746-d69b53875a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-toast-message-content</value>
      <webElementGuid>c2475703-c73d-4a9f-b9bb-a70349ea0aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>messagecontent</value>
      <webElementGuid>5627b9bc-f8a6-424b-a2ff-9df94c03aa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NotificationUpdate property specification successfully.</value>
      <webElementGuid>4b7f0714-1e6e-4bb1-9f6b-cb71d8f4b768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;p-toast-message p-toast-message-success&quot;]/div[@class=&quot;p-toast-message-content&quot;]</value>
      <webElementGuid>50e4d629-d122-44f6-9139-59f14047fa6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NotificationUpdate property specification successfully.' or . = 'NotificationUpdate property specification successfully.')]</value>
      <webElementGuid>1b1351f9-8e15-477f-80d2-74ab4ffa492c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
