<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_edit</name>
   <tag></tag>
   <elementGuidId>d0237bc2-79c4-4ca9-9713-939b7bf160bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.p-button-contrast</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[45]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @data-p-severity = 'contrast' and (text() = 'Save' or . = 'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Save&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc4e04c9-e87a-4358-9853-66ed4c81de86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-contrast</value>
      <webElementGuid>3d580fe6-499f-4935-a113-5e45f23d44f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>158f6a01-650d-4313-a71f-7404b4185ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>3126dbbb-52fe-4b4f-8cab-f537ca2f97ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb09daa2-a65d-4957-ad6c-7b0dcbbd4d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7599c135-00f0-4e54-a227-bf3571913d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-severity</name>
      <type>Main</type>
      <value>contrast</value>
      <webElementGuid>1cd483ef-68b9-4b1e-b089-48821e517394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>80cb13f5-f171-4195-96ae-94972e702181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>02034b6b-a431-4dd2-9255-41b9971d8345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_136_tabpanel_General&quot;)/div[@class=&quot;h-full flex flex-col overflow-auto&quot;]/div[@class=&quot;flex items-center gap-4 footer&quot;]/button[@class=&quot;p-button p-component p-button-contrast&quot;]</value>
      <webElementGuid>ef9683c6-b577-4bf8-bfc0-2b472cdf0009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[45]</value>
      <webElementGuid>48a29b7f-2802-430e-b465-71b7bb205493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_136_tabpanel_General']/div/div[2]/button</value>
      <webElementGuid>8f1bb7c2-5be8-4447-aa8b-f92267357974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[1]/following::button[1]</value>
      <webElementGuid>01c2780f-6207-4d0f-af60-f3b7d024016e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>db76cc6e-3765-4b3a-9e47-f0b2ae3e2469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>293cfb34-f516-4d88-abe3-90d9608c6762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>f1b67d7c-592e-4844-bfed-328d3d47795b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
