<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NotificationDelete selected product group successfully</name>
   <tag></tag>
   <elementGuidId>c1eaed03-fb80-429c-881d-be15d90731c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/divă</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-toast-message-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'p-toast-message-content' and @data-pc-section = 'messagecontent' and (text() = 'NotificationDelete selected product group successfully.' or . = 'NotificationDelete selected product group successfully.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;NotificationDelete selected product group successfully.&quot;i >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa21e78b-ce87-4423-8cb1-354b42895e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-toast-message-content</value>
      <webElementGuid>69aa3729-8114-4867-a820-ae294722806d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>messagecontent</value>
      <webElementGuid>379aae6b-d3e8-4f48-9cb2-8c733b068b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NotificationDelete selected product group successfully.</value>
      <webElementGuid>71b9fceb-c7fd-4e17-ab06-ac7ad1b770ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;p-toast p-component p-toast-top-right&quot;]/div[1]/div[@class=&quot;p-toast-message p-toast-message-success p-toast-message-leave-active p-toast-message-leave-to&quot;]/div[@class=&quot;p-toast-message-content&quot;]</value>
      <webElementGuid>50b3eb22-28c8-4229-b969-74d04595af6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>0e865c52-b9d3-4669-b1a4-896553133f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NotificationDelete selected product group successfully.' or . = 'NotificationDelete selected product group successfully.')]</value>
      <webElementGuid>7cc901d5-c684-4a72-9603-7813baedea69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
