<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_trash_item</name>
   <tag></tag>
   <elementGuidId>dc6f63ea-47c1-453a-b493-ca986e05ca36</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[td[text()='${code}']]//span[contains(@class, 'pi-trash')]&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'pi pi-trash' and @pgCode = '${pgCode}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pi.pi-trash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;name name2  &quot;i] >> internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@app/epc']/div/div/div[4]/div/div/div/div/div[2]/div[2]/div/table/tbody/tr/td[5]/div/a[2]/span</value>
      <webElementGuid>1669244c-bc81-4368-b3fd-3e65d5233cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>56408f34-456b-4dc1-9bb7-4f4bffd3c915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
