<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_In study</name>
   <tag></tag>
   <elementGuidId>9d92f32b-1ea2-4363-8023-7afedb3d2732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pv_id_162&quot;)/span[@class=&quot;p-select-label&quot;][count(. | //span[@class = 'p-select-label' and @tabindex = '0' and @role = 'combobox' and @aria-label = 'In study' and @aria-haspopup = 'listbox' and @aria-expanded = 'false' and @aria-controls = 'pv_id_162_list' and @aria-disabled = 'false' and @data-p = 'clearable' and @data-pc-section = 'label' and (text() = 'In study' or . = 'In study')]) = count(//span[@class = 'p-select-label' and @tabindex = '0' and @role = 'combobox' and @aria-label = 'In study' and @aria-haspopup = 'listbox' and @aria-expanded = 'false' and @aria-controls = 'pv_id_162_list' and @aria-disabled = 'false' and @data-p = 'clearable' and @data-pc-section = 'label' and (text() = 'In study' or . = 'In study')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_162']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_162 > span.p-select-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;In study&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c123a546-c194-4bfc-aa2e-416441815124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-select-label</value>
      <webElementGuid>877521e2-9150-4ebe-bc74-0cb650576257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce23ebb2-f51e-48da-b6a3-1a2f938c6425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>d1199846-5db9-4a8e-a1a7-12f1967d4f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>In study</value>
      <webElementGuid>20a75462-f193-49ef-9357-1652867871fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>9874d7b3-ed8b-4b5e-9a32-fd525f82fb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d68ea8d-7b20-4720-b47a-451b1e367e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pv_id_162_list</value>
      <webElementGuid>d841bc1c-5b9b-4365-8b65-19117fbfe039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b78f91a9-b178-45a8-b240-456b88ba5dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p</name>
      <type>Main</type>
      <value>clearable</value>
      <webElementGuid>963abf00-c686-43b2-bf20-4c08532c5367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fa67bf7d-e396-4800-890a-c1bc9397e966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In study</value>
      <webElementGuid>a9b00bdc-85aa-4e98-8b75-cef86b184fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_162&quot;)/span[@class=&quot;p-select-label&quot;]</value>
      <webElementGuid>516b1fed-135a-4d0c-8288-a1fcb56432c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_162']/span</value>
      <webElementGuid>2a9404ce-f1f1-4511-adc1-c3762bbc7531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::span[1]</value>
      <webElementGuid>2d0a10d8-8e86-4ac7-8b8c-405536f5b47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ValidFor'])[1]/following::span[6]</value>
      <webElementGuid>2f32281b-51bf-443e-8a6c-9f47132a6a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[1]/preceding::span[1]</value>
      <webElementGuid>3ecbb1cd-0675-42ce-bda6-f8c5b537973a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::span[4]</value>
      <webElementGuid>f708a7f1-0c33-4fa4-81c8-f79cace9f601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='In study']/parent::*</value>
      <webElementGuid>2adb7a8f-aa52-4fa9-8fad-324fae30f887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/span</value>
      <webElementGuid>7f38427e-4d22-4ab3-9d8c-cdaa5b837626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'In study' or . = 'In study')]</value>
      <webElementGuid>0ab4660a-f50c-4e48-aa5c-706aaae8b3df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
